### ISSUE TITLE
running: import runai.ga.keras gives: ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by badlammajamma** [run-ai/runai#26]
When I attempt import runai.ga.keras I get this strange error:
```
 ### Imports ###
import os
import tensorflow as tf 
import numpy as np
import keras as K
import cv2
import sys
import math
import pickle
import psutil
import runai.ga.keras
```
returns:

```
  File "C:\Users\user\.conda\envs\TF_EDS\lib\site-packages\runai\utils\flock.py", line 1, in <module>
    import fcntl

ModuleNotFoundError: No module named 'fcntl'
```
I am running a virtual env via conda. 

OS: Windows 10
Python: 3.83
Tensor Flow: 2.4.0
Keras: 2.4.3

**Comment by levosos** [comment]
Hi @badlammajamma and thanks for reaching out!

Currently, our library uses `fcntl` as a dependency which is not available on Windows.
Technically, this dependency is relevant for using `runai.hpo` which you don't use, so we can avoid trying to import it when using other modules (e.g. `runai.ga`).

In addition to that, you are using TF and Keras versions which [we do not currently support](https://github.com/run-ai/runai/issues/21#issuecomment-668095434), and probably won't do it anytime soon.

In case you are willing to downgrade your versions of TF and Keras to supported ones, we'll be willing to help with the issue you are encountering now.

Let us know, and thanks again for reaching out!

**Comment by badlammajamma** [comment]
Thank you!
